### ISSUE TITLE
"Which food is better" 

### ISSUE THREAD

**Issue by fliiiix** [optikfluffel/what-food-is-worse#15]
Rename project to  "Which food is better" 'cause positive thinking :+1:

**Comment by fliiiix** [comment]
Kann man das Github-repo umbenennen ohne das alles kaputt geht?

**Comment by optikfluffel** [comment]
mal ausprobieren? aber dein Link in der Mail vorhin bricht dann

**Comment by fliiiix** [comment]
hm stimmt besser nicht
